version: '3'

services:
   web:
      build: .
      volumes:
         - .:/code
      ports:
         - 8000:8000
      command: python /code/music_player/manage.py runserver 0.0.0.0:8000
      depends_on:
         - db
   db:
      image: postgres
      environment:
         - POSTGRES_DB=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
      container_name: postgres_db