version: '3'
services:
   backend:
      build: 
         context: .
         dockerfile: Dockerfile-B 
      volumes:
         - ./backend:/code
      ports:
         - 8000:8000  
      command: python /code/music_player/manage.py runserver 0.0.0.0:8000
      depends_on:
         - db
   db:
      image: postgres
      environment:
         - POSTGRES_DB=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
      container_name: postgres_db
   frontend:
      build: 
         context: .
         dockerfile: Dockerfile-F    
      volumes:
         - ./frontend:/app
      ports:
         - "3000:8080"
      depends_on:
         - backend
      command: npm run serve