# Generated by Django 3.2.6 on 2021-08-21 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_createddatetime_usercomments_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomments',
            old_name='usename',
            new_name='username',
        ),
    ]
