# Generated by Django 3.2.6 on 2021-08-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usename', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=5000)),
                ('timeStamp', models.CharField(max_length=4)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
