# Generated by Django 3.2.6 on 2021-08-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomments',
            old_name='createdDateTime',
            new_name='created_at',
        ),
    ]
