# Generated by Django 3.2.6 on 2021-08-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_usename_usercomments_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
